@extends('site.layouts.content')
{{-- Web site Title --}}
@section('title')
Capilla
@parent
@stop

{{-- Content --}}
@section('content-left')

<div class="col-sm-12">
<!-- Main Page Content -->
<div id="main-page-content" class="section-container main-page-content clearfix">

		<div class="section-content clearfix">

		<h1 class="page_title">La Capilla</h1>

				<p>
				
				<p style="text-align: justify;" mce_style="text-align: justify;">Nos encontramos en la Capilla de la "Real, Ilustre y Fervorosa Hermandad del Sant&iacute;simo Sacramento y Archicofrad&iacute;a Sacramental y Cofrad&iacute;a de Nazarenos de la Sagrada Expiraci&oacute;n de Nuestro Se&ntilde;or Jesucristo y Mar&iacute;a Sant&iacute;sima de las Aguas", conocida popularmente como <strong>Capilla de la Hermandad del Museo. </strong></p>
				<p style="text-align: justify;" mce_style="text-align: justify;">La Hermandad fue fundada en el a&ntilde;o 1575 en la Iglesia Parroquial de San Andr&eacute;s. Cuentan que un grupo de fieles&nbsp; devotos, pertenecientes mayoritariamente al gremio de plateros,&nbsp; quedaron impresionados al escuchar como el sacerdote describ&iacute;a los sufrimientos padecidos por Nuestro Se&ntilde;or Jesucristo durante la Expiraci&oacute;n y decidieron crear una Hermandad cuyo titular fuera un Cristo que representara ese tr&aacute;gico momento. De hecho, desde sus or&iacute;genes, ha sido conocida como la Hermandad de la Expiraci&oacute;n. Al a&ntilde;o siguiente de la fundaci&oacute;n la hermandad se traslada al convento de la Merced Calzada (actual Museo de Bellas Artes) y posteriormente adquieren unos terrenos anexos al convento donde levantan esta Capilla. El patrimonio art&iacute;stico que vamos a describir est&aacute; indisolublemente unido al devenir hist&oacute;rico de nuestra corporaci&oacute;n.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">En el exterior habr&aacute; observado la fachada, donde destaca un <strong>retablo cer&aacute;mico</strong> con las im&aacute;genes del Cristo de la Expiraci&oacute;n y, a sus pies, Nuestra Se&ntilde;ora de la Aguas. Su autor fue el ceramista Antonio Morilla Galea, que lo ejecut&oacute; en 1963. Adem&aacute;s de su indudable valor art&iacute;stico, permite el culto a nuestros titulares en todo momento.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Una vez en el interior nos encontramos con un espacio rectangular. En el techo apreciamos un artesonado de madera decorado con casetones tallados y policromados en cuyas intersecciones aparece inscrito el primitivo escudo de la Hermandad. Fue realizado a finales del siglo XVII. El suelo est&aacute; cubierto por una soler&iacute;a de m&aacute;rmol ajedrezado, recuerda a la original de m&aacute;rmol de G&eacute;nova que, durante la invasi&oacute;n francesa de la ciudad, el Mariscal Soult mand&oacute; fuera retirada y depositada en el palacio Arzobispal, donde &eacute;l resid&iacute;a en esos momentos. Bajo el escudo de la Cruz de Jerusal&eacute;n que podemos ver en la soler&iacute;a hay una entrada a una antigua cripta de enterramiento, rehabilitada y usada como columbario, donde se depositan las cenizas de los hermanos fallecidos que as&iacute; lo hayan dispuesto.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">En la cabecera de la Capilla encontramos el retablo mayor, de estilo neocl&aacute;sico, dividido en tres calles, la central presenta una hornacina donde se dan culto a las im&aacute;genes titulares y es enmarcada por dos columnas a cada lado.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">El <strong>Cristo de la Expiraci&oacute;n</strong> fue realizado por Marcos Cabrera en el 1575, y obedece al canon manierista. Es un crucificado de tama&ntilde;o natural, que representa el momento en que Jes&uacute;s&nbsp; exhala el &uacute;ltimo aliento. Fue ejecutado en pasta de madera y policromado, posteriormente se le a&ntilde;adi&oacute; el sudario de telas encoladas sustituyendo as&iacute; el primitivo, que era una pieza de lino que se le ajustaba a la cintura. La leyenda dice que la Hermandad puso como condici&oacute;n al escultor que los moldes fueran arrojados al&nbsp; Guadalquivir para as&iacute; impedir que se realizaran copias de la imagen.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">A sus pies, <strong>Mar&iacute;a Sant&iacute;sima de las Aguas</strong>, imagen de candelero con rostro y busto&nbsp; modelado en terracota por Crist&oacute;bal Ramos en 1772. La imagen fue concebida de rodillas y con las manos entrelazadas en actitud de oraci&oacute;n. A lo largo del tiempo se le han realizado varias modificaciones hasta alcanzar su estado actual. Puede observarse que no porta corona, sino diadema, y habitualmente, un tul liso dispuesto al modo monjil, que resalta su natural belleza. La imagen destaca por su serenidad, naturalidad y realismo, que la hace cercana y genera gran devoci&oacute;n.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">En el banco del retablo mayor, a los pies de la Virgen de las Aguas, se encuentra el <strong>Sagrario</strong>, dise&ntilde;ado&nbsp; por Manuel Guzm&aacute;n Bejarano y realizado en plata por Juan Borrero.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">En las calles laterales del retablo se disponen los <strong>cuatro evangelistas</strong>, que tallara Francisco Antonio Ruiz Gij&oacute;n entre 1682 y 1689. Todos ellos llevan, adem&aacute;s de sus respectivos atributos: <strong>San Juan</strong> (&aacute;guila), <strong>San Lucas</strong> (Toro), <strong>San Marcos</strong> (Le&oacute;n) y <strong>San Mateo</strong> (Hombre/&aacute;ngel), una pluma y un libro, a excepci&oacute;n de San Lucas que lleva un pergamino. Est&aacute;n considerados como verdaderas obras maestras del barroco sevillano, tanto por lo atrevido y perfecci&oacute;n de su talla como por su policrom&iacute;a.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Siguiendo el sentido de las agujas del reloj vamos a recorrer los distintos altares que se disponen en la capilla. A la derecha encontramos un altar obra del siglo XVII, aunque ha sufrido muchas transformaciones. En la hornacina principal su centro se venera una espl&eacute;ndida imagen manierista de <strong>Cristo atado a la columna o Cristo flagelado</strong>, que fue realizado entre 1583 y 1585 atribuido a Jer&oacute;nimo Hern&aacute;ndez. Destacan la perfecci&oacute;n de sus formas art&iacute;sticas. En el banco del retablo hay una peque&ntilde;a hornacina donde se encuentra una Virgen Dolorosa de candelero.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">A continuaci&oacute;n encontramos un retablo realizado a mediados del siglo XVIII, alberga a <strong>Nuestra Se&ntilde;ora del Rosario</strong>, atribuida a Jer&oacute;nimo Hern&aacute;ndez&nbsp; sobre el a&ntilde;o de 1577. Virgen sedente, en sus brazos la figura de Jes&uacute;s Ni&ntilde;o portando una Cruz. En el banco del retablo hay una hornacina donde podemos observar la peque&ntilde;a figura de un&nbsp; <strong>Nazareno</strong>, es una imagen de vestir articulada.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Siguiendo el recorrido observamos el retablo donde se encuentra la imagen de <strong>San Ram&oacute;n Nonato</strong>, el busto es&nbsp; atribuido a afamado imaginero Juan de Mesa (Siglo XVI). Debe su nombre a que su nacimiento se produjo despu&eacute;s de haber fallecido su madre. Viste el h&aacute;bito blanco de la Orden Mercedaria, sobre el cual lleva la esclavina color p&uacute;rpura propia de su condici&oacute;n cardenalicia; porta un ostensorio o custodia en la mano derecha, y en la izquierda la palma con tres coronas (castidad, elocuencia y martirio)&nbsp; que distinguen a los m&aacute;rtires de la fe. Cuenta la leyenda que San Ram&oacute;n Nonato fue hecho&nbsp; cautivo y, a&uacute;n as&iacute;, continu&oacute; predicando el evangelio. Para impedirlo le abrieron agujeros a hierro candente en sus labios para colocarle un candado y cerrar su boca. Nuestra Hermandad siempre ha estado ligada a la Orden Mercedaria, que fue fundada por San Pedro Nolasco para el rescate de los cautivos cristianos que eran apresados y llevados al norte de &aacute;frica. Mantiene gran devoci&oacute;n por ser el santo patr&oacute;n de los partos, parteras, ni&ntilde;os, y&nbsp; las embarazadas.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Le sigue, sobre una repisa, una imagen de tama&ntilde;o acad&eacute;mico de <strong>Santa Luc&iacute;a,</strong> tal como se representa con una palma en una mano (s&iacute;mbolo de martirio) y en la otra la bandeja con sus ojos. Es obra an&oacute;nima del siglo XVIII.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Bajo el coro de la Capilla, sobre un frontal de azulejer&iacute;a trianera, de estilo renacentista y datado en 1626, se levanta la portentosa escultura barroca de <strong>Nuestra Se&ntilde;ora de la Merced</strong> sentada sobre un sill&oacute;n de coro. &nbsp;Majestuosa, se&ntilde;orial, presenta los ropajes tallados y decorados con ricos estofados, con t&uacute;nica, escapulario y manto abrochado con el escudo mercedario. Sostiene en su mano izquierda un libro, y la derecha la apoya sobre el pecho. Est&aacute; atribuida con mucho fundamento a Jos&eacute; Montes de Oca, y fechada sobre el a&ntilde;o de 1732. Su iconograf&iacute;a representa una antigua tradici&oacute;n mercedaria que narra como San Pedro Nolasco y sus monjes se retrasaron&nbsp; en su obligaci&oacute;n de acudir al coro, pues se qued&oacute; dormido el encargado de hacer sonar la campana que los convocaba habitualmente al rezo de las horas en el templo conventual. Cuando llegaron se encontraron a los &aacute;ngeles ocupando sus respectivos sitiales y a la Virgen presidiendo el Coro y dirigiendo el oficio de maitines. Es por ello que, desde entonces, se la tuvo como <strong>La Comendadora</strong>, portando en su mano el libro de Horas. En el caso de esta talla sevillana, fue tambi&eacute;n conocida, popularmente, como la Virgen del Rayo por haber salido indemne tras una terrible tormenta que destroz&oacute; el Coro de la Iglesia conventual</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Siguiendo el sentido de las agujas del reloj encontramos la imagen de <strong>San Lorenzo</strong>, representado como es costumbre con el instrumento de su martirio, una parrilla. Es una obra an&oacute;nima del barroco sevillano, fechable en el siglo XVIII.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Finalmente, cercana al altar mayor, en el seno de una hornacina abierta en el muro, destaca el magn&iacute;fico grupo escult&oacute;rico en que se representa a <strong>Santa Ana con la  Virgen Ni&ntilde;a</strong>, talla de madera policromada atribuida a Benito Hita y Castillo sobre el a&ntilde;o de 1750.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Sobre los muros, se exponen varios cuadros de tem&aacute;tica religiosa. Sin embargo,&nbsp; en&nbsp; el&nbsp; terreno&nbsp; pict&oacute;rico,&nbsp; no podemos&nbsp; contemplar lo&nbsp; que fuera&nbsp; la&nbsp; joya de la Capilla, el imponente lienzo debido a Bartolom&eacute; Esteb&aacute;n Murillo en el que se representa la Resurrecci&oacute;n del Se&ntilde;or, cuadro expoliado por el Mariscal Soult cuando la invasi&oacute;n francesa, llevado a Francia en 1811, y posteriormente devuelto al Gobierno Espa&ntilde;ol, dejando el cuadro en Madrid, integrado en el patrimonio del Museo del Prado y depositado en la&nbsp;  Real Academia de Bellas Artes de San Fernando en Madrid. As&iacute; mismo, fue expoliado otro cuadro - tambi&eacute;n propiedad de esta Hermandad de la  Sagrada Expiraci&oacute;n -, debido al pincel del pintor sevillano Francisco Varela, que representaba la Oraci&oacute;n en el Huerto.</p>
				<p style="text-align: justify;" mce_style="text-align: justify;">Existen otras obras art&iacute;sticas de orfebrer&iacute;a, bordado, talla, etc., que forman parte de los enseres de esta Archicofrad&iacute;a del Lunes Santo sevillano, que el resto del a&ntilde;o permanecen expuestas en las vitrinas existentes en las dependencias anexas a la Capilla.</p>
				
							
				</p>

				</div><!-- .section-content -->

				</div><!-- .section-container -->
				<!-- End: Main Page Content -->
				</div><!-- .col-sm-12 -->

@stop
				